
services:
  - type: web
    name: dsa-chatbot
    runtime: python
    buildCommand: ""
    startCommand: "gunicorn app:app"
    envVars:
      - key: API_KEY
        value: your_api_key_here
